### ISSUE TITLE
Pagination to download >100 tours

### ISSUE THREAD

**Issue by MartenGoettsche** [ThePBone/KomootGPX#3]
Hi,
the script currently only downloads/lists the first 100 tours because it's not aware of the pagination used by komoot api.
The api response includes the HAL-link to the next page: e.g.: 
"_links":{"self":{"href":"https://api.komoot.de/v007/users/xxxxxxxxxxxxx/tours/"},"next":{"href":"https://api.komoot.de/v007/users/xxxxxxxxxxxxx/tours/?page=1&limit=100"}},"page":{"size":100,"totalElements":154,"totalPages":2,"number":0}}'

**Comment by ThePBone** [comment]
Hey,
thanks for reporting this issue.

Commit 3e0780c72154b1a87521d163299af035bb1871ca adds support for pagination in the API client.
